Vylepšení kódu - striktního typování a reorganizace adresářové struktury
bosancz/bosan.cz pull request #355
Opened 2021-04-04 15:12 UTC by SmallhillCZ

Je to docela brutální zásah, je potřeba ozkoušet naživo.

 - Striktní typování Typescriptu a s tím související přepsání některých částí kódu
 - Adresářová struktura dle nejnovějšího Angular Style Guide

2021-04-04 22:36 UTC, DavidTvrdy requested changes
Našel jsem pár odlišností, nevím, jak moc jsou relevantní, každopádně jsou tu:

1) Seznam blogů nemá sloupeček _publikováno_. Neumím posoudit, jestli naschvál, ale stávající interní ho má.

2) Seznam blogů se mi často nenačte (nebo se načítá tak dlouho, že nemám trpělivost čekat a dávám refresh), načte se potom na několikátý pokus (nebo třeba po zapnutí nějakého filtru, ale to možná byla náhoda).

3) Na kartě konkrétní akce (př. Přehled/Volné akce, Akce/Detail akce) se u akcí bez vedoucího zobrazuje místo _Vede pan Nikdo_ pouze _Vede_.

2021-04-05 01:38 UTC, SmallhillCZ commented
Kouknu na to zítra.

2021-04-05 09:49 UTC, SmallhillCZ commented
@DavidTvrdy

1) jo, blog je zatím jen takové torzo. v novém layoutu jsem to dost předělal.
2) to se mi taky stávalo, ale v nové verzi se mi to už neděje, tak jsem to neřešil. každopdáně to nesouvisí s tímhle, takže OK.
3) opraveno, dík!

2021-04-05 10:16 UTC, DavidTvrdy approved these changes

2021-04-05 10:32 UTC, merged