Nový mobile-first layout
bosancz/bosan.cz pull request #356
Opened 2021-04-04 15:18 UTC by SmallhillCZ

2021-05-17 09:15 UTC, krystofrezac commented
Mám nastavenej prohlížeč na tmavej režim, ale web pořád někde ukazuje bílý plochy. 
A další věc je, že i když mám světlej režim, tak v kladendáři jsou akce hrozně nečitelný.
![Screenshot from 2021-05-17 11-09-24](https://user-images.githubusercontent.com/39591095/118463989-a7ead480-b700-11eb-9e4f-ba1fa6a6e6d7.png)

2021-05-17 12:59 UTC, SmallhillCZ commented
Uf co je tohle za magii... žádnej tmavej režim! :-D

2021-05-17 13:27 UTC, SmallhillCZ commented
@krystofrezac udělal jsem nějaký velmi hrubý úpravy aby ti to v noci nevypálilo oči, ale jinak bych to vyčlenil do vlastní feature. nechci už tohle nafukovat.

2021-05-18 08:49 UTC, SmallhillCZ commented
Přidávám screenshoty s chybami od Tweety
![chyba_2](https://user-images.githubusercontent.com/1273865/118621294-85bb8a00-b7c6-11eb-8fae-b6a41dee483d.png)

![chyba_1](https://user-images.githubusercontent.com/1273865/118621302-86ecb700-b7c6-11eb-9569-ba2f508d82cd.png)

2021-05-18 08:54 UTC, SmallhillCZ commented
![chyba_1](https://user-images.githubusercontent.com/1273865/118622239-6a9d4a00-b7c7-11eb-80d0-b1c2b26645cf.png)

2021-05-18 13:23 UTC, DavidTvrdy commented
(M1)
V sekci Uživatelé se mi neukáže žádný uživatel, i když u filtru je napsáno Role: všechny. Ve skutečnosti je asi filtr nastaven tak, aby neukazoval nic.

2021-05-18 13:24 UTC, DavidTvrdy commented
(M2)
V sekci Uživatelé nefunguje tlačítko Lupa pro otevření/zavření vyhledávání a filtru, filtr a vyhledávání nejdou skrýt.

2021-05-18 13:31 UTC, DavidTvrdy commented
(M3)
V Moje akce je počítadlo dnů. Vypadá to, že u každé akce odečte jeden den.

2021-05-18 13:32 UTC, SmallhillCZ commented
@DavidTvrdy  M1: hele mně to funguje, můžeš mi dát nějaký detaily? jako třeba na čem si to prohlížíš

2021-05-18 13:33 UTC, SmallhillCZ commented
@DavidTvrdy M2: tlačítko lupy dáno pryč

2021-05-18 13:35 UTC, DavidTvrdy commented
(M4)
Jen nápad:
Když v účtování upravuji částku a zadám neplatný vstup, nemohlo by mi to nějak dát najevo (červené podtržení např.)?
Může se to stát třeba u desetinných míst, která se zobrazují v seznamu oddělená čárkou, ale v kolonce pro vyplnění částky je potřeba zadat je s tečkou.

2021-05-18 13:38 UTC, DavidTvrdy commented
> 
> 
> @DavidTvrdy M1: hele mně to funguje, můžeš mi dát nějaký detaily? jako třeba na čem si to prohlížíš

Desktop, Firefox 88.0.1, účet bilbo

2021-05-18 13:39 UTC, SmallhillCZ commented
@DavidTvrdy M4: hm... v chromu ta čárka nevadí a nic jinýho ti to zadat nedovolí

2021-05-18 13:52 UTC, DavidTvrdy commented
(M6)
Tlačítko přidat uživatele v sekci Uživatelé nemá obrázek, tlačítko není vidět, ale je tam.

Desktop, Firefox 88.0.1

2021-05-18 13:56 UTC, SmallhillCZ commented
Stáhl jsem si Firefox a všechno v něm funguje nějak divně. Ale nevim, co s tím. Stránky se občas načtou pomalu, občas vlbec, občas chybí nějaký text, úplný haluze.

2021-05-18 13:57 UTC, SmallhillCZ commented
@DavidTvrdy M6: opraveno

2021-05-18 14:00 UTC, DavidTvrdy commented
(M7)
Jako člen a vedoucí můžu upravovat účtování (a členy) akcí, které nevedu. Je to správně?

2021-05-18 14:01 UTC, SmallhillCZ commented
@DavidTvrdy M7: to není, kouknu na to, asi jsem to moc neřešil. podaří se ti to uložit? to by nemělo. jen se ti zobrazí to rozhraní na editaci

2021-05-18 14:05 UTC, DavidTvrdy commented
(M8)
Když smažu nějakou položku z účetnictví, tak to trochu zmate automatický vyplňovač políčka ID u dalších položek. 
Místo aby mi navrhnul nejnižší volné číslo dokladu nebo vymazané věci ignoroval a pokračoval v počítání od nejvyššího posledního čísla nebo aby se automaticky čísla dokladů snížily, tak mi navrhne (počet_aktuálních_položek + 1).

2021-05-18 14:07 UTC, DavidTvrdy commented
> 
> 
> @DavidTvrdy M7: to není, kouknu na to, asi jsem to moc neřešil. podaří se ti to uložit? to by nemělo. možná se ti jen zobrazí to rozhraní na editaci


Aha, jen se mi zobrazí rozhraní a změna se mi ukáže, ale neuloží se, při dalším otevření akce už změnu nevidím.

2021-05-18 14:13 UTC, SmallhillCZ commented
@DavidTvrdy

M7 opraveno

M8 opraveno

2021-05-18 14:22 UTC, DavidTvrdy commented
(M9)
V Přehled akcí (Akce) se nezobrazuje ve sloupci Místo nic, i když je u akce místo vyplněné.
Potřebujeme tam sloupec Místo vůbec?

2021-05-18 14:24 UTC, DavidTvrdy commented
(M10)
Tlačítko Plus pro vytvoření akce v Přehledu akcí (Akce) mě pustí do rozhraní pro vytvoření akce, i když na to nemám práva. Když pak v rozhraní kliknu na tlačítko Vytvořit, tak mě to odhlásí, při opětovném přihlášení jsem zase v tom rozhraní. 
Akce se teda nevytvoří..

2021-05-18 14:32 UTC, DavidTvrdy commented
> 
> 
> @DavidTvrdy
> 
> M7 opraveno
> 
> M8 opraveno

 M7: Teď už se nemůžu na report, přihlášku, účtování, účastníky podívat. Nešlo by něco z toho tam nechat viditelné a jen zakázat tlačítka pro úpravu (viz diskuze u closed #191).

2021-05-18 14:45 UTC, DavidTvrdy commented
(M11)
Změna data u alba se v seznamu alb projeví až po obnovení stránky.
Navíc není problém zadat neplatné datum, třeba konec před začátkem.

2021-05-18 14:46 UTC, DavidTvrdy commented
(M12)
V detailu alba se uvádí Název, Datum začátku a Popisek. Nebylo by lepší, kdyby tam bylo celé datum?

2021-05-18 14:50 UTC, DavidTvrdy commented
(M13)
Když chci do alba nahrát fotky, tak po vybrání odpovídajících fotek neumím v jejich seznamu scrollovat, takže nemůžu kliknout na tlačítka Nahrát nebo Zrušit.

Desktop, Firefox 88.0.1

2021-05-18 14:52 UTC, DavidTvrdy commented
(M14)
Popisky u fotek se v detailu alba na fotkách zobrazí až po obnovení stránky.

2021-05-18 14:54 UTC, DavidTvrdy commented
(M15)
Když zruším publikaci fotoalba, tak mu zůstane ve sloupci Publikováno v Přehledu alb pořád datum poslední publikace.

2021-05-18 15:08 UTC, DavidTvrdy commented
(M16)
Hodnota v sloupci Autoři v přehledu příspěvků blogu se nedá nijak nastavit.

2021-05-18 15:24 UTC, SmallhillCZ commented
Díky moc, kouknu na to zas zítra!

2021-05-18 15:28 UTC, DavidTvrdy commented
(M17)

![image](https://user-images.githubusercontent.com/47000101/118679775-75bf9c80-b7fe-11eb-9e51-0fd46545f0b0.png)

2021-05-18 15:40 UTC, DavidTvrdy commented
(M18)
Není problém vytvořit akci s koncem dřív než je začátek.

2021-05-18 15:46 UTC, DavidTvrdy commented
(M19)
Správce programu (ne vedení, ne revizor, ne správce webu) může upravovat účtování a účastníky akcí, které nevede; změny se uloží. To by asi neměl - je to správně?

2021-05-18 15:54 UTC, DavidTvrdy commented
(M20)
Je možné, aby někdo měl účet s právy Člen, ale ne Vedoucí?
Takový člen může vidět přehled akcí a detaily akcí (včetně účastníků a účtování).

2021-05-18 16:01 UTC, DavidTvrdy commented
(M21)
Člen vedení nevidí report z akce.
Revizor nevidí report z akce.

2021-05-18 16:02 UTC, DavidTvrdy commented
(M22)
Revizor má k dispozici kartu Uživatelé (má mít?). Když na ní klikne, tak ho web odhlásí.

2021-05-18 16:43 UTC, DavidTvrdy commented
(M23)

![Screenshot_2021-05-18-18-41-28-765_com android chrome](https://user-images.githubusercontent.com/47000101/118691035-f7b4c300-b808-11eb-8581-5ddd2d6fa1bf.jpg)

2021-05-18 16:45 UTC, DavidTvrdy commented
(M24)

![Screenshot_2021-05-18-18-37-26-328_com android chrome](https://user-images.githubusercontent.com/47000101/118691231-2894f800-b809-11eb-84df-be0b6795caca.jpg)

2021-05-18 16:46 UTC, DavidTvrdy commented
(M25)

![Screenshot_2021-05-18-18-37-35-794_com android chrome](https://user-images.githubusercontent.com/47000101/118691385-52e6b580-b809-11eb-883a-df41a0feb5f4.jpg)

2021-05-18 16:47 UTC, DavidTvrdy commented
(M26)

![Screenshot_2021-05-18-18-39-39-301_com android chrome](https://user-images.githubusercontent.com/47000101/118691530-77429200-b809-11eb-9c6c-cba48d89693a.jpg)

2021-05-18 16:48 UTC, DavidTvrdy commented
(M27)

![Screenshot_2021-05-18-18-41-11-709_com android chrome](https://user-images.githubusercontent.com/47000101/118691668-97725100-b809-11eb-8dba-82f715579109.jpg)

2021-05-18 17:26 UTC, Grejdy requested changes
Když smažu fotku z alba a pak překliknu z „fotky“ do „album“, tak se tam pořád zobrazuje, dokud se opětovně stráka nenačte (není to nijak závažný nedostatek, ale může to mást, takže možná by se to vyřešit mohlo)

2021-05-18 17:34 UTC, Grejdy reviewed
Je správně, že jde nahrát i třeba 11 megabajtovou fotku? (jako uživatel to beru, jako zlepšení, ale nevím, kde jsou ty fotky uložené a jestli tam to dřívější omezení nebylo třeba kvůli omezené kapacitě disku, nebo něco takovýho)

2021-05-18 17:47 UTC, Grejdy requested changes
Obdobný problém, jako u akcí i při přidávání členů do databáze - Není problém zadat datum narození, které ještě nenastalo (tzn. může být v databázi vedoucí, který se má za dva týdny narodit). Otázkou je, jestli to řešit (nepředpokládám, že někdo do databáze bude přidávat cíleně někoho nenarozeného) a jestli omezit obecné přidávání, nebo i nastavit třeba minimální věk pro to, aby mohl mít někdo status instruktor atp.

2021-05-18 17:51 UTC, Grejdy commented
Možnost psát k lidem počet hvězd přibude podobně, jako alergie a kartička pojištěnce, až v nějakém dalším updatu?

2021-05-19 06:35 UTC, Grejdy commented
otázka: Jak se liší (nebo přinejmenším by se měly lišit) ty role? Nejsem si jistý, co (nebo koho) si mám představit pod kterou rolí, jaké má mít práva a třeba jak se liší člověk bez role a člověk s rolí „člen“.

2021-05-19 07:13 UTC, Grejdy requested changes
Na mobilu není vůbec vidět charakter akce. Dalo by se to vyřešit podle mě třeba tím, že neaktivní charaktery by byly zesvětlené a ne ztmavené. (+ návrh:nešlo by nějak přidat ke každé ikonce charakteru i popisek, ať to není jen nicneříkající kolečko)
![obrazek](https://user-images.githubusercontent.com/82664677/118770581-caf0c200-b881-11eb-91f1-6bfe050e2ad7.png)

2021-05-19 07:35 UTC, Grejdy requested changes
Na mobilu se nezobrazuje přihláška a tlačítko oteřít nefunguje (Android 10, prohlížeč: Vivaldi 3.8.2267.29). Zkoušel jsem to i v jiném prohlížeči (DuckDuckGo 5.85.3) a tam se nezobrazí ani to (ale stáhnout normálně jde).
![obrazek](https://user-images.githubusercontent.com/82664677/118773943-95e66e80-b885-11eb-97bd-3cc8a458ea43.png)

2021-05-19 07:52 UTC, Grejdy requested changes
V tmavém režimu nejsou vidět tlačítka při upravování databáze (jsou tam, ale na tom tmavém pozadí nejsou vidět)
![obrazek](https://user-images.githubusercontent.com/82664677/118776096-e6f76200-b887-11eb-8030-e70a28af85a9.png)

2021-05-19 07:55 UTC, Grejdy commented
Co má být ten blog?

2021-05-19 08:08 UTC, Grejdy reviewed
Na mobilu ve vivaldim mi často nejde scrollovat. (Jiné stránky normálně fungujou a Když jsem to samé zkoušel ještě v Seznam prohlížeči a DuckDuckGo, tak to normálně fungovalo. Problém mám opravdu jen v kombinaci testovací stránky-Vivaldi prohlížeč)

2021-05-19 08:12 UTC, Grejdy requested changes
Záložka  „uživatelský účet“ je na mobilu v takovém dost na houby rozložení, kdy jsou vedle sebe dva uzoučké samostatné sloupce. (prohlížeče Seznam a DuckDuckGo)

2021-05-20 12:44 UTC, SmallhillCZ commented
@Grejdy to nemůžeš mít nějaký normální prohlížeč? :-D Kouknu na to, ale jestli by to bylo nějak extra složité, dáme to do kategorie `wont fix`

2021-05-20 12:45 UTC, SmallhillCZ commented
> Co má být ten blog?

To je do budoucna, zatím to má jen úpravu v interní a ve veřejné sekci se to nezobrazuje.

2021-05-20 12:47 UTC, SmallhillCZ commented
> otázka: Jak se liší (nebo přinejmenším by se měly lišit) ty role? Nejsem si jistý, co (nebo koho) si mám představit pod kterou rolí, jaké má mít práva a třeba jak se liší člověk bez role a člověk s rolí „člen“.

teď nijak - to byl nějaký plán s tím, že by měli účet i rodiče, třeba na přihlášení svých dětí a rozlišovalo se kdo je člen a kdo externí

každopádně je to mimo scope tohoto PR

2021-05-20 12:50 UTC, SmallhillCZ commented
> V tmavém režimu nejsou vidět tlačítka při upravování databáze (jsou tam, ale na tom tmavém pozadí nejsou vidět)

@Grejdy  Jaký tlačítka?

2021-05-20 12:52 UTC, SmallhillCZ commented
> Na mobilu není vůbec vidět charakter akce, když je stránka zobrazena v tmavém režimu. Dalo by se to vyřešit podle mě třeba tím, že neaktivní charaktery by byly zesvětlené a ne ztmavené. To samé i u výběru oddílů na akci.(+ návrh:nešlo by nějak přidat ke každé ikonce charakteru i popisek, ať to není jen nicneříkající kolečko)

@Grejdy 
1) Jak jsme řešili výše s Mazákem, dark mode uděláme při nějaké další změně nějak komplexně a tady vyřdešíme jen když něco vysloveně nebude vidět/fungovat.
2) Ono to kolečko kromě toho obrázku nemá žádný jiný smysl ;) Je to jen grafický prvek.

2021-05-20 13:10 UTC, SmallhillCZ commented
> (M21)
> Člen vedení nevidí report z akce.
> Revizor nevidí report z akce.

@DavidTvrdy nikdo nevidí report z akce :) tohle ještě neni implementovaný, jen jsem to přenesl ze starý, protože je to furt v plánu

2021-05-20 13:19 UTC, SmallhillCZ commented
> (M22)
> Revizor má k dispozici kartu Uživatelé (má mít?). Když na ní klikne, tak ho web odhlásí.

má, revizor má vidět všehcno, ale nemá mít možnost změny. opraveno.

2021-05-20 13:32 UTC, SmallhillCZ commented
> (M17)
> 

To je nějaký problém s tím editorem. To vyřešíme jindy.

2021-05-20 13:36 UTC, SmallhillCZ commented
> (M19)
> Správce programu (ne vedení, ne revizor, ne správce webu) může upravovat účtování a účastníky akcí, které nevede; změny se uloží. To by asi neměl.

Může, zatím nerozlišujeme různé editace jedné akce. A Správce programu má právo editovat libovolnou akci. Asi bych to tak nechal, není tu podle mě žádná hrozba, že by ti Leila mazala lidi na akci ;)

2021-05-20 13:52 UTC, SmallhillCZ commented
> Možnost psát k lidem počet hvězd přibude podobně, jako alergie a kartička pojištěnce, až v nějakém dalším updatu?

Jj, tenhle PR se týká změny layoutu, funkcionality jsou jen přenesené ze staré interní. Někdy je doděláme.

2021-05-20 13:54 UTC, DavidTvrdy commented
> > (M21)
> > Člen vedení nevidí report z akce.
> > Revizor nevidí report z akce.
> 
> @DavidTvrdy nikdo nevidí report z akce :) tohle ještě neni implementovaný, jen jsem to přenesl ze starý, protože je to furt v plánu

Aha, nevšiml jsem si, že je taky pak vidět v přehledu akce. Moje chyba..

2021-05-20 13:56 UTC, DavidTvrdy commented
> > (M19)
> > Správce programu (ne vedení, ne revizor, ne správce webu) může upravovat účtování a účastníky akcí, které nevede; změny se uloží. To by asi neměl.
> 
> Může, zatím nerozlišujeme různé editace jedné akce. A Správce programu má právo editovat libovolnou akci. Asi bych to tak nechal, není tu podle mě žádná hrozba, že by ti Leila mazala lidi na akci ;)

Aha, ok.

2021-05-20 14:00 UTC, Grejdy commented
> 
> 
> @Grejdy to nemůžeš mít nějaký normální prohlížeč? :-D Samozřejmě na to kouknu, ale jestli by to bylo nějak extra složité, dáme to do kategorie `wont fix`

Já se snažím pokud možno vyhýbat googlu, microsoftu a facebooku, takže z těch nejobvyklejších prohlížečů popužívám vlastně jenom firefox.:-)

Jinak ty problémy s androidovým Vivaldim asi opravdu budou na vyřešení moc složité na to, jak závažný je to problém. Vivaldi je více méně nástupce Opery a je to dost specifický prohlížeč, takže třeba na tom mobilu se vlastně tváří, jako by byl na linuxu a není na něm problém i třeba otevřít stránky, u kterých google normálně řve, že je na mobilu otevře jen ve speciální aplikaci. Na druhou stranu se moc nedivím že u něčeho takovýho může být problém.

2021-05-20 14:02 UTC, SmallhillCZ commented
> Na mobilu se nezobrazuje přihláška a tlačítko oteřít nefunguje (Android 10, prohlížeč: Vivaldi 3.8.2267.29). Zkoušel jsem to i v jiném prohlížeči (DuckDuckGo 5.85.3) a tam se nezobrazí ani to (ale stáhnout normálně jde).

Nj, to zobrazování PDF na mobilu nefunguje. Ale to není problém nového layoutu, tak to nechávám,

2021-05-20 14:04 UTC, Grejdy commented
> 
> 
> > otázka: Jak se liší (nebo přinejmenším by se měly lišit) ty role? Nejsem si jistý, co (nebo koho) si mám představit pod kterou rolí, jaké má mít práva a třeba jak se liší člověk bez role a člověk s rolí „člen“.
> 
> teď nijak - to byl nějaký plán s tím, že by měli účet i rodiče, třeba na přihlášení svých dětí a rozlišovalo se kdo je člen a kdo externí
> 
> liší se co vím tak:
> 
>     * bez role
> 
>     * vedoucí (může editovat a vést akce a do databáze)
> 
>     * správce programu (může měnit stav akcí)
> 
>     * správce webu (může editovat vše)

dík. to je určitě dobrý nápad. Napadá mě, že by se tím mohla udělat i třeba notifikace o nové akci, nějaký kecací prostor pod akcí (aby se komunikace s rodiči mohla odehrávat tam místo mailu atp.). V takovém případě by se ale hodil i jiný způsob, jak se dostat do veřejné sekce, než se odhlásit.

2021-05-20 14:05 UTC, SmallhillCZ commented
> Já se snažím pokud možno vyhýbat googlu, microsoftu a facebooku

Ty musíš mít těžkej život :-D

2021-05-20 14:06 UTC, SmallhillCZ commented
> > > otázka: Jak se liší (nebo přinejmenším by se měly lišit) ty role? Nejsem si jistý, co (nebo koho) si mám představit pod kterou rolí, jaké má mít práva a třeba jak se liší člověk bez role a člověk s rolí „člen“.
> > 
> > 
> > teď nijak - to byl nějaký plán s tím, že by měli účet i rodiče, třeba na přihlášení svých dětí a rozlišovalo se kdo je člen a kdo externí
> > liší se co vím tak:
> > ```
> > * bez role
> > 
> > * vedoucí (může editovat a vést akce a do databáze)
> > 
> > * správce programu (může měnit stav akcí)
> > 
> > * správce webu (může editovat vše)
> > ```
> 
> dík. to je určitě dobrý nápad. Napadá mě, že by se tím mohla udělat i třeba notifikace o nové akci, nějaký kecací prostor pod akcí (aby se komunikace s rodiči mohla odehrávat tam místo mailu atp.). V takovém případě by se ale hodil i jiný způsob, jak se dostat do veřejné sekce, než se odhlásit.

Do veřejné sekce se dostaneš tak, že zadáš bosan.cz, ne? Na to se nemusíš odhlašovat...

2021-05-20 14:06 UTC, Grejdy commented
> Na

Asi úplně nevím, co tím myslíš... (moc se tu zatím nevyznám)

2021-05-20 14:12 UTC, SmallhillCZ commented
> > @Grejdy Tohle je přebrané ze staré verze, problém to je, ale ne v kontextu tohohle PR (nový > layout). Uděláš z toho kdyžtak pls normální Issue?
> 
> Asi úplně nevím, co tím myslíš... (moc se tu zatím nevyznám)

Zadat to tady, protože to nesouvisí s tím novým layoutem: https://github.com/bosancz/bosan.cz/issues/new/choose

2021-05-20 14:13 UTC, Grejdy commented
> 
> 
> > V tmavém režimu nejsou vidět tlačítka při upravování databáze (jsou tam, ale na tom tmavém pozadí nejsou vidět)
> 
> @Grejdy Jaký tlačítka?

Konkrétně třeba okýnko na „fajfku“ u možnosti neaktivní a šipky, zobrazující výběr. Když o tom člověk ví, tak to nevadí, ale není z toho pro nezasvěcence jasné, co to dělá. (ve světlé verzi je to tam takovou světle šedivou)

2021-05-20 14:20 UTC, Grejdy commented
>     2. Ono to kolečko kromě toho obrázku nemá žádný jiný smysl ;) Je to jen grafický prvek.

To ne. Ale je z toho vidět právě to, o jakou akci se cca. bude jednat, což je dobrý. Možná by nebylo špatný, kdyby k tomu byl i nějaký popisek aspoň třeba při rozkliknutí, nebo něco takového, ať nezasvěcení vedoucí nematou rodiče tím, že tam prostě dají obrázek, co se jim líbí, jelikož neznají poselství obrázků (myslím, že v nějaké verzi na počítači už to bylo, že po najetí myši se zobrazil textík typu „Akce po Praze“). Ale asi to není úplně prvořadá priorita.:-)

2021-05-20 14:31 UTC, Grejdy commented
>     2. Do veřejné sekce se dostaneš tak, že zadáš bosan.cz, ne? Na to se nemusíš odhlašovat...

Ad 2: Ale je to takový... no nic moc.

2021-05-20 19:41 UTC, sv-ignac commented
V tmavém režimu v sekci program nejsou některé kategorie vidět. Obecně bílé písmo v kalendáři v podbarvených akcí je špatně čitelné.
![image](https://user-images.githubusercontent.com/82539505/119039045-1f945a00-b9b4-11eb-8403-c779cc4a438c.png)

2021-05-20 19:55 UTC, sv-ignac commented
V tmavém režimu je editace popisku fotky neviditelná

2021-05-20 19:58 UTC, sv-ignac commented
Nešlo by udělat to, aby při popisu fotky člověk klikl jen do řádku a "otevřelo" se pro editaci. Pokaždé klikat na tu ikonu vpravo je při popisování 200 fotek z tábora pěkný opruz. :)

2021-05-20 20:02 UTC, sv-ignac commented
Pokud chci fotky řadit, tak obě funkce (jméno a datum) řadí dle data. Chápu to tedy tak, že jméno je ten popisek, co udělám. Pokud je to název souboru, tak to jo.

2021-05-20 20:09 UTC, sv-ignac commented
V tmavém režimu v Databázi není vidět člen - Klubu přátel. Přitom tam je. :)
![image](https://user-images.githubusercontent.com/82539505/119042320-f4136e80-b9b7-11eb-8430-40c6ebdec1a0.png)
![image](https://user-images.githubusercontent.com/82539505/119042388-0f7e7980-b9b8-11eb-8171-1696772873af.png)

2021-05-21 07:36 UTC, SmallhillCZ commented
> > ```
> > 2. Do veřejné sekce se dostaneš tak, že zadáš bosan.cz, ne? Na to se nemusíš odhlašovat...
> > ```
> 
> Ad 2: Ale je to takový... no nic moc.

Můžu ti tam do interní dát někam odkaz jestli tě to potěší

2021-05-21 07:43 UTC, SmallhillCZ commented
@sv-ignac @Grejdy @DavidTvrdy udělal jsem na Dark mode separé Issue #372 . Tady vyřešíme jen problémové věci, které třeba nejsou vůbec vidět.

2021-05-21 07:44 UTC, SmallhillCZ commented
> Nešlo by udělat to, aby při popisu fotky člověk klikl jen do řádku a "otevřelo" se pro editaci. Pokaždé klikat na tu ikonu vpravo je při popisování 200 fotek z tábora pěkný opruz. :)

@sv-ignac editace popisku se otevře buď, když zmáčkneš enter, nebo když na to dvakrát klikneš

2021-05-21 07:46 UTC, SmallhillCZ commented
> Pokud chci fotky řadit, tak obě funkce (jméno a datum) řadí dle data. Chápu to tedy tak, že jméno je ten popisek, co udělám. Pokud je to název souboru, tak to jo.

@sv-ignac  Je to název souboru. To je pro případ, že je tam datum blbě (třeba se vzalo z poslední editace fotky), ale ty soubory se logicky jmenujou z foťáku podle pořadí (IMG001.JPG, IMG002.JPG, ...)

Seřadit dle popisku můžu, ale nevidím ten smysl uplně

2021-05-21 07:59 UTC, SmallhillCZ commented
> V tmavém režimu v Databázi není vidět člen - Klubu přátel. Přitom tam je. :)

Jo, no... protože KP má nastavenou černou barvu. Asi tohle vyřešíme až v té #372

2021-05-21 14:44 UTC, SmallhillCZ commented
Jinak bych rád zdůraznil, že jste skvělí! :) Začíná to vypadat, že bychom to mohli vypustit do světa.

2021-05-21 18:37 UTC, Grejdy commented
> 
> 
> > > ```
> > > 2. Do veřejné sekce se dostaneš tak, že zadáš bosan.cz, ne? Na to se nemusíš odhlašovat...
> > > ```
> > 
> > 
> > Ad 2: Ale je to takový... no nic moc.
> 
> Můžu ti tam do interní dát někam odkaz na veřejnou, jestli tě to potěší

jo, to by bylo super, jestli ti to nedělá problém.

2021-05-23 17:25 UTC, SmallhillCZ commented
Tak snad by všechno, co dývalo smysl, mělo být opraveno. Jestli ještě někdo do zítra něco nepřidá, pošlu to do světa.

2021-05-24 10:49 UTC, merged