Serverový docker image založený na Apline Linux verzi NodeJS image
bosancz/bosan.cz pull request #361
Opened 2021-04-19 12:43 UTC by SmallhillCZ

Tahle změna není nijak viditelná, jen ulehčí našemu serveru. Balík serveru už nebude mít 1,1 GB, ale jen 250 MB. Dalo by se pokročit ještě daleko dál, spousta z instalovaných NPM balíčků se nepoužije. K tomu by se musel použít webpacku tree shaking (odebrání nepoužitého kódu).

## Změny

 - V Dockerfile se image netvoří z `node:14.16` ale z `node:14.16-alpine`

## Testovací scénář

Cílem je otestovat, jestli se nic nerozbilo.

 1. Přihlásit se na `test.bosan.cz` a proklikat web, vytvořit akci, album atd.
 2. Napsat feedback, buď `Approve review`, nebo `Request changes`. Návod zde: [Jak na testování](https://github.com/bosancz/bosan.cz/wiki/Jak-na-testov%C3%A1n%C3%AD%3F)

2021-04-19 13:51 UTC, Grejdy commented
Nemůžu najít to okýnko, co je v Jak na testování (takové to review changes, approve atp.), ale každopádně myslím, že jsem na jeden problém narazil. Nějak se mi na ten test.bosan nejde přihlásit (přihlašuju se, jako normálně - přezdívka, heslo - stejné jako na normálním webu - a pořád to tvrdí, že nemám správné heslo, a to jsem si i kontroloval na normálním webu, takže pokud pro testovací verzi nejsou jiné přihlašovací údaje tak tam asi něco špatně je.

2021-04-19 13:56 UTC, SmallhillCZ commented
Jo, to bude starou databází... Stejně byste ale měli mít vlastně větší přístup, než svůj standardní. 

Vytvořím účet a pošlu detaily na mail.

2021-04-19 14:01 UTC, Grejdy requested changes
Myslím, že jsem našel problém. Při opakovaném pokusu o přihlášení tvrdí, že mám špatné jméno/heslo (kontroloval jsem si to ve veřejné verzi a jsem si celkem jistý, že se přihlašuji správně. (pokud nejsou pro testovací verzi jiné přihlašovací údaje, než pro tu veřejnou.)

2021-04-19 15:08 UTC, SmallhillCZ commented
@Grejdy: tak na mailu byste měli mít nové přihlašovací údaje a s těmi by to mělo už fungovat ;)

2021-04-19 16:25 UTC, Grejdy submitted a review, later dismissed
občas mi stránka zamrzne a nejsem si jistý, jestli to je mnou, prohlížečem, nebo kódem. ještě to můžu večer zkusit na jiném prohlížeči. každopádně se mi nepovedlo zadat vedoucího akce (přes vést akci ani přes řádek vedoucí, možná by to mohlo souviset s tím, že tam není databáze - třeba se mu nelíbí, že vedoucí akce oficiálně neexistuje nebo něco takového). ještě na to kouknu až budu mít čas, ale zatím jsem našel tohle. kdyby to nějak pomohlo, tak jsem to zkoušel na windows 10 v Seznam prohlížeči.

2021-04-19 16:41 UTC, Tweety6 commented
Mně bohužel nejde vytvořit akci

2021-04-19 17:01 UTC, TomasNeumann commented
Asi spíše vlastnost - ale nepraktická.
Po kliknutí na rozbalovací "Program" v horní liště, se rozbalí a zůstane rozbalen i pokud kliknu jinam - intuitivnější by mi přišlo pokud by se při takové akci opět zabalil.

2021-04-19 17:58 UTC, SmallhillCZ commented
@TomasNeumann jo, to je ale mimo scope tohoto PR. Normálně bych ti řekl, abys udělal Issue, ale v tomhle případě jen počkej na nový layout, protože to bude všechno jinak ;)

2021-04-19 17:59 UTC, SmallhillCZ commented
@Tweety6 : budeš mi muset napsat víc, protože mně to funguje a i je tam už pár vytvořených akcí od někoho. Hlásí to nějakou chybu? Jde zmáčkonout tlačítko? Děláš to z počítač,e nebo z mobilu? Dík!

2021-04-20 09:07 UTC, Tweety6 approved these changes
Už vše funguje.

2021-04-20 09:10 UTC, merged