Upgrade balíčků
bosancz/bosan.cz pull request #439
Opened 2021-11-16 00:35 UTC by SmallhillCZ

# Změny

 - balíčky (programy) na kterých stojí interní sekce jsem aktualizoval na nejnovější verze
 - angular je teď ve verzi 13
 - typescript 4.4
 - ionic 5.8

# Testovací scénář

Cílem je ověřit, jestli se novými verzemi nic nepokazilo

 1. otevři si https:// test.bosan.cz
 2. zkontroluj, že verze je 3.0.13
 3. proklikej web a koukni, jestli něco není rozbité
 4. Napsat feedback, buď `Approve review`, nebo `Request changes`. Návod zde: [Jak na testování](https://github.com/bosancz/bosan.cz/wiki/Jak-na-testov%C3%A1n%C3%AD%3F)

2021-11-16 15:48 UTC, Grejdy requested changes
Píše mi to „Verze 3.0.12“. Nevím, jestli se to jenom nepřepsalo, nebo jestli se tam ta aktualizace ještě nenahrála (znovu načíst jsem zkoušel a na adrese test.bosan.cz jsem)

2021-11-17 09:45 UTC, Grejdy requested changes
Nefunguje přihlšení (zadám jméno, heslo, zmáčknu přihlásit a nic se nestane; pc, různé prohlížeče).
A to jak na testovací stránce tak na té oficiální!!!!

2021-11-17 11:02 UTC, mk185283 commented
> Nefunguje přihlášení (zadám jméno, heslo, zmáčknu přihlásit a nic se nestane; různá zařízení, různé prohlížeče). A to jak na testovací stránce tak na té oficiální!!!!

Bohužel potvrzuji, že se nelze dostat do https://interni.bosan.cz - žádná vypsaná chyba, nelze přes heslo ani přes google account. :(
@SmallhillCZ šlo by na to přednostně kouknout prosím?

2021-11-17 14:12 UTC, SmallhillCZ commented
Hm... to asi nesouvisí s timhle, ale něco se asi posralo :)

2021-11-17 14:15 UTC, SmallhillCZ commented
Zrestartoval jsem to a funguje to. Nějak umřela databáze 🤷‍♀️

2021-11-17 14:16 UTC, SmallhillCZ commented
@Grejdy já jsem tenhle PR dal zatím pryč, protože jsem potřeboval dát nejdřív tu opravu na veřejné a nasazuje se to spolu. Pošlu ho teď na server.

2021-11-17 14:51 UTC, Grejdy requested changes
Na mobilu nefunguje tlačítko vést akci. (pro role člen, vedoucí, revizor) Na počítači nebo s vyššími pravomocemi to funguje normálně.

2021-11-17 20:06 UTC, DavidTvrdy commented
> 
> 
> Na mobilu nefunguje tlačítko vést akci. (pro role člen, vedoucí, revizor) Na počítači nebo s vyššími pravomocemi to funguje normálně.

Zkoušel jsem to teda jenom na jedné akci, ale vypadá to, že mi to funguje..

2021-11-17 21:28 UTC, sv-ignac commented
Ahoj,
zkoušel jsem to jen nan počítači. Zkoušel jsem růžně upravovat, proklikávat sekce a možnosti. Přijde mi, že mi to fungovalo. Co jsem se chtěl spíš zeptat, zda by se nedalo udělat něco s oknem při úpravě/zadávání akce. Je tam hrozně malý rámeček na zadávání popisu a dole je zbytečně místo. Nevím, zda to není jen mým rozložením obrazovky nebo to neslouží na něco, co se mi zrovna nezobrazovalo, že tam nebylo zadáno. (viz. screen.)
![image](https://user-images.githubusercontent.com/82539505/142285236-3d659a38-841e-42c0-8969-53344e1ac817.png)
Díky

2021-11-18 16:55 UTC, Grejdy commented
> 
> 
> Na mobilu nefunguje tlačítko vést akci. (pro role člen, vedoucí, revizor) Na počítači nebo s vyššími pravomocemi to funguje normálně.

jo, tak už mi to funguje taky. nevím, kde byl problém.

2021-11-18 16:56 UTC, Grejdy approved these changes
v tom případě myslím, že je vše v pohodě

2021-11-19 18:05 UTC, Grejdy commented
Jinak neví někdo co je s veřejnou sekcí? Vypadá to, že se veškerý obsah upravitelný v interní sekci nemá v plánu načíst. Včera jsem si říkal, že je třeba problém se spojením, nebo tak něco, ale nefunguje to doteď.

2021-11-21 08:00 UTC, SmallhillCZ commented
> Jinak neví někdo co je s veřejnou sekcí? Vypadá to, že se veškerý obsah upravitelný v interní sekci nemá v plánu načíst. Včera jsem si říkal, že je třeba problém se spojením, nebo tak něco, ale nefunguje to doteď.

Jo, byl to ten stejný problém jako nedávno s interní. Nějak se pokazilo spojení s databází. Udělal jsem na to Issue s návrhem řešení #443.

2021-11-21 08:02 UTC, SmallhillCZ commented
> Ahoj, zkoušel jsem to jen nan počítači. Zkoušel jsem růžně upravovat, proklikávat sekce a možnosti. Přijde mi, že mi to fungovalo. Co jsem se chtěl spíš zeptat, zda by se nedalo udělat něco s oknem při úpravě/zadávání akce. Je tam hrozně malý rámeček na zadávání popisu a dole je zbytečně místo. Nevím, zda to není jen mým rozložením obrazovky nebo to neslouží na něco, co se mi zrovna nezobrazovalo, že tam nebylo zadáno. (viz. screen.) ![image](https://user-images.githubusercontent.com/82539505/142285236-3d659a38-841e-42c0-8969-53344e1ac817.png) Díky

Jo, to by asi neměl být problém. Udělal jsem k tomu separátní Issue #444 , snad se toho někdo chytí. Co, @JakubRejzek?

2021-11-21 08:03 UTC, merged