Vylepšené upravování fotek
bosancz/bosan.cz pull request #456
Opened 2022-01-17 22:50 UTC by SmallhillCZ

Ještě na tom pracuji, ale můžete se podívat ;)

# Změny

 - na rozkliknuté fotce je tlačítko Smazat
 - fotky jde otevírat i z přehledu alba
 - otevřená fotka se ukáže v URL, takže na ní lze odkazovat

# Testovací scénář

 1.
 X. Napsat feedback, buď `Approve review`, nebo `Request changes`. Návod zde: [Jak na testování](https://github.com/bosancz/bosan.cz/wiki/Jak-na-testov%C3%A1n%C3%AD%3F)

2022-01-18 20:25 UTC, DavidTvrdy requested changes
Koukal jsem na to, vypadá to super!

Našel jsem několik drobností:

(1) Při postupném prohlížení fotek v tom modalu vidím pořád popisek fotky, kterou jsem otevřel jako první, až do doby, kdy se ho pokusím upravit nebo do doby, než si nechám zobrazit info fotky.
Vyjimkou je přepínání fotek pomocí šipek na klávesnici, při tom to funguje v pohodě.

(2) Po kliknutí na Info nefunguje trik 'Enter-text-Enter' pro úpravu popisku. Sice se aktivuje upravování popisku, ale nejde tam psát, a zároveň se otevře (nebo zůstane otevřené) info.

(3) Taková ta ikonka s počtem fotek se nerada aktualizuje (je potřeba refresh).

(4) Tlačítko Publikovat / Zrušit publikaci má stejný problém jako v (3).

(5) Tohle už je delší dobu, ale teď jsem si toho víc všimnul - když zruším publikaci alba, mohlo by se datum v kolonce Publikováno smazat. Teď mi to přijde matoucí, když vidím, "Ovocné zátiští, publikováno 18. 1. 2022" a vedle toho tlačítko Publikovat, protože album ve skutečnosti ve veřejné sekci zrovna není.

2022-01-19 07:17 UTC, Grejdy requested changes
Totéž, co psal Mazák v bodu (1) a (3) platí i na androidu (s tím rozdílem, že mobil nemá klávesnici, kde by šlo používat šipky:-)). S tím by možná bylo dobrý něco udělat. V praxi by to mohlo být poměrně matoucí.

2022-01-19 08:39 UTC, Grejdy requested changes
Všiml jsem si, že (minimálně na mobilu, předpokládám, že na počítači to tak bude taky) přibyla kolonka s datem publikace, která umožňuje přepsat datum publikace (jediná regulace tam je, že tam něco musí být, ale klidně tam může být i dřívější datum, než datum vytvoření alba). Tahle kolonka se automaticky přepíše, když se zmáčkne publikovat (pak jde zase přepsat zpátky). Nejsem si jistý, jaký to má mít účel (nebo jestli to není prostě chyba), ale řekl bych, že by se s tím ještě něco mělo udělat. A přejmenoval bych to z „Publikováno“ třeba na „Publikace“ (přesně ať pak není vedle tlačítka „Publikovat“ nápis „Publikováno tehdy a tehdy“)

2022-01-19 10:31 UTC, DavidTvrdy commented
> Totéž, co psal Mazák v bodu (1) a (3) platí i na androidu (s tím rozdílem, že mobil nemá klávesnici, kde by šlo používat šipky:-)). S tím by možná bylo dobrý něco udělat. V praxi by to mohlo být poměrně matoucí.

Jo všechno bylo myšleno Android/Desktop.

2022-01-19 10:36 UTC, DavidTvrdy commented
> Všiml jsem si, že (minimálně na mobilu, předpokládám, že na počítači to tak bude taky) přibyla kolonka s datem publikace, která umožňuje přepsat datum publikace (jediná regulace tam je, že tam něco musí být, ale klidně tam může být i dřívější datum, než datum vytvoření alba). Tahle kolonka se automaticky přepíše, když se zmáčkne publikovat (pak jde zase přepsat zpátky). Nejsem si jistý, jaký to má mít účel (nebo jestli to není prostě chyba), ale řekl bych, že by se s tím ještě něco mělo udělat. A přejmenoval bych to z „Publikováno“ třeba na „Publikace“ (přesně ať pak není vedle tlačítka „Publikovat“ nápis „Publikováno tehdy a tehdy“)

Podle toho data se galerie řadí ve veřejné sekci na stránce Aktuálně (jsou tam myslím vidět tři neskrytá alba s nejnovějším datem publikace). Přijde mi to takhle dobrý, možnost upravit to přímo a i zpětně mi přijde jako super zlepšení!

2022-01-19 12:04 UTC, Grejdy commented
> 

Jo tak. Tak to dává smysl. Ale stejně bych to aspoň přejmenoval a možná k tomu napsal, k čemu to je - když člověk neví, co to je, tak tam prostě něco napíše a bude v tom ještě větší zmatek (nebo to v lepším případě nechá prázdný)

2022-01-19 15:32 UTC, SmallhillCZ commented
> Koukal jsem na to, vypadá to super!
> 
> Našel jsem několik drobností:
> 
> (1) Při postupném prohlížení fotek v tom modalu vidím pořád popisek fotky, kterou jsem otevřel jako první, až do doby, kdy se ho pokusím upravit nebo do doby, než si nechám zobrazit info fotky. Vyjimkou je přepínání fotek pomocí šipek na klávesnici, při tom to funguje v pohodě.
> 
> (2) Po kliknutí na Info nefunguje trik 'Enter-text-Enter' pro úpravu popisku. Sice se aktivuje upravování popisku, ale nejde tam psát, a zároveň se otevře (nebo zůstane otevřené) info.
> 
> (3) Taková ta ikonka s počtem fotek se nerada aktualizuje (je potřeba refresh).
> 
> (4) Tlačítko Publikovat / Zrušit publikaci má stejný problém jako v (3).
> 
> (5) Tohle už je delší dobu, ale teď jsem si toho víc všimnul - když zruším publikaci alba, mohlo by se datum v kolonce Publikováno smazat. Teď mi to přijde matoucí, když vidím, "Ovocné zátiští, publikováno 18. 1. 2022" a vedle toho tlačítko Publikovat, protože album ve skutečnosti ve veřejné sekci zrovna není.

(1) chyba, opravím

(2) chyba, opravím

(3+4) hm... nad tím se budu muset zamyslet víc

(5) jo to by asi mohlo, zkusím to tak udělat

2022-01-22 13:00 UTC, SmallhillCZ commented
Opravil jsem 1), 2), 4) a 5), je to ve verzi 3.1.1, prosím zkontrolujte.

2022-01-22 14:00 UTC, Grejdy requested changes
Problém (1) na mobilu zůstal (na pc už v pohodě).
Problém (2) se na pc vyskytne znovu, pokud po rozklikutí „info“ kliknu do pole s infem - podle animací myslím, že kliknutím do pole sice pole zmizí, ale pořád zůstane načtené a „rozkliknuté“ a je potřeba znovu někam kliknout, aby fotka začla reagovat na klávesnici (problikne znova animace zavírání infa a je to v pohodě - do té doby to však vypadá, že to má fungovat a nefunguje).
Bod (5) vyřešen, ale tak, že po zrušení publikace zmizí datum a pod názvem alba zůstane jen text „Publikováno“. Možná by vypadalo líp, kdyby tam byla třeba dvojtečka („Publikováno: 22. 1. 2022“ ->„Publikováno:   “), případně s nějakým textem pro prázdnou hodnotu („Publikováno: 22. 1. 2022“->„Publikováno: zatím ne“), případně by mohl text „Publikováno“ při zrušení publikace proste zmizet společně s datem.

Ukázka bodu (2) (snad z toho bude vidět ten problém):


https://user-images.githubusercontent.com/82664677/150641340-0c57f5a1-5fae-48fe-a20c-bc36e93d4c99.mp4

2022-01-23 10:18 UTC, DavidTvrdy commented
> @DavidTvrdy , @Grejdy: Opravil jsem 1), 2), 4) a 5), je to ve verzi 3.1.1, prosím zkontrolujte.

1) Za mě vyřešeno (mě to funguje všude).
4) Vyřešeno.
5) Vyřešeno. (Jo asi by tam mohla zůstat ta dvojtečka, jak píše Grejdy..)

2022-01-23 10:27 UTC, DavidTvrdy commented
> @DavidTvrdy , @Grejdy: Opravil jsem 1), 2), 4) a 5), je to ve verzi 3.1.1, prosím zkontrolujte.


(2) ... Na Androidu vyřešeno.
Na PC jsou 2 problémy:

(2a) Kliknutí na pole s infem posune pole s infem **pod** obrázek (místo aby se nestalo nic), takže se zdá, že tam už není (je tam, je tam kousek vidět, kliknutím na něj se dá zase zpět posunout nahoru).

(2b) Animace zavření pole s infem je u mě (Firefox 96.0.2) většinou (ne vždy) nějaká divná. Vypadá si takhle: instantní zmizení -> instantní objevení -> postupné zmizení. Měla by vypadat jen jako postupné zmizení. Ale asi mi to nijak nevadí.

2022-01-23 10:31 UTC, Grejdy commented
> > @DavidTvrdy , @Grejdy: Opravil jsem 1), 2), 4) a 5), je to ve verzi 3.1.1, prosím zkontrolujte.
> 
> (1) Za mě vyřešeno (mě to funguje všude). (4) Vyřešeno. (5) Vyřešeno. (Jo asi by tam mohla zůstat ta dvojtečka, jak píše Grejdy..)

Potvrzuji, že bod (1) je v pořádku. Už mi to taky funguje. (možná jenom déle trvalo, než se dostala nová verze i na mobil)

2022-01-23 10:41 UTC, Grejdy commented
> > @DavidTvrdy , @Grejdy: Opravil jsem 1), 2), 4) a 5), je to ve verzi 3.1.1, prosím zkontrolujte.
> 
> (2) ... Na Androidu vyřešeno. Na PC jsou 2 problémy:
> 
> (2a) Kliknutí na pole s infem posune pole s infem **pod** obrázek (místo aby se nestalo nic), takže se zdá, že tam už není (je tam, je tam kousek vidět, kliknutím na něj se dá zase zpět posunout nahoru).
> 
> (2b) Animace zavření pole s infem je u mě (Firefox 96.0.2) většinou (ne vždy) nějaká divná. Vypadá si takhle: instantní zmizení -> instantní objevení -> postupné zmizení. Měla by vypadat jen jako postupné zmizení. Ale asi mi to nijak nevadí.

Jo, tohle bude asi to, co se mi tam nezdá. Ono totiž nejen že se posune, ale zároveň reaguje na klávesy, jako enter a šipky místo obrázku (resp. nereguje, protože nemá žádné reakce nastavené). Výsledný dojem je, že zpoza obrázku vykukuje kus infa a fotka nereaguje na klávesnici.

2022-01-24 16:46 UTC, SmallhillCZ commented
**(2a a 2b)**: tohle je asi nějaká browser issue, kterou se mi nedaří v Chromu zreplikovat.

(3) snad opraveno, musel jsem část celou předělat

Jinak byl problém, když se zavřelo procházení fotek a pak zas otevřelo, to jsem vyřešil.

2022-01-24 17:19 UTC, SmallhillCZ commented
Tak ještě nějaký divný konflikt npm, takže to bude **3.1.3**

2022-01-24 17:52 UTC, Grejdy commented
> ### Verze 3.1.2:
> 
> **(2a a 2b)**: tohle je asi nějaká browser issue, kterou se mi nedaří v Chromu na desktopu ani na Androidu zreplikovat.
> 
> **(3)**: snad opraveno, musel jsem část celou předělat
> 
> A byl problém, když se zavřelo procházení fotek a pak zas otevřelo, pak nefungovalo to že některá kávesy nic nedělají dokud je info otevřeno, jak říkal @Grejdy, to byla chyba v tom frameworku Ionic co používáme, kterou mezi tím vyřešili.
> 
> @Grejdy "možná jenom déle trvalo, než se dostala nová verze i na mobil" - musíš zkontrolovat číslo verze v menu dole. Pokud není ta nová, tak to chce chvíli počkat, než se zobrazí žlutý nápis, že je nová verze a pak na něj kliknout. Jestli se nezobrazí, tak buď není ještě připravená (chvíli poté, co ji sem nahraju) nebo dej refresh.

Jo něco takovýho jsem si myslel, že to je.

2022-01-24 18:12 UTC, Grejdy commented
(3) je v pohodě (na mobilu i v počítači). Budeš se pokoušet ještě nějak vyřešit tu (2a a 2b) @SmallhillCZ, nebo jí neumíme vyřešit a budem prostě doufat, že si toho nikdo nevšimne?

2022-01-25 10:58 UTC, SmallhillCZ commented
Jako řešil bych to určitě, ale říkám si, jestli z toho neudělat separátní issue, aby to zbytečně neblokovalo tohle.

2022-01-25 11:02 UTC, merged