Fix/development environment
bosancz/bosan.cz pull request #568
Opened 2023-04-18 13:06 UTC by SmallhillCZ

# Změny

 - upgrade všech balíčku, hlavně Angularu, tak, aby to fungovalo s NodeJS v18

# Testovací scénář

1. Naklonuj si čistou verzi pomocí `git clone`
2. Spusť `npm ci --force` aby se nainstalovaly balíčky (force je tam kvůli jedné nekonzistenci, která nevadí a bude asi brzo vyřešená)
3. Spusť `npm run dev:test` a vyzkoušej, jestli funguje

 Po otestování vždy napiš feedback, buď `Approve review`, nebo `Request changes`. Návod zde: [Jak na testování](https://github.com/bosancz/bosan.cz/wiki/Jak-na-testov%C3%A1n%C3%AD%3F)

2023-04-18 17:15 UTC, Grejdy commented
> 2\. (force je tam kvůli jedné nekonzistenci, která nevadí a bude asi brzo vyřešená)

„Bude brzo vyřešená“ znamená, že se to vyřeší samo a teď se smíříme s tím, že musíme psát o slovo víc a budem si to pamatovat?

2023-04-18 19:55 UTC, Grejdy requested changes
![obrazek](https://user-images.githubusercontent.com/82664677/232889438-0a15251f-e08b-45bf-b946-fa799d13faee.png)
Něco tam nesedí.

2023-04-18 21:41 UTC, SmallhillCZ commented
> ![obrazek](https://user-images.githubusercontent.com/82664677/232889438-0a15251f-e08b-45bf-b946-fa799d13faee.png)
> Něco tam nesedí.

Udělal jsi čistou instalaci balíčků, nebo to jen spustil znovu na existujících? Vypadá to, že tam máš z nějakého důvodu starý jeden (klíčový) balíček - typescript.

2023-04-19 08:29 UTC, Grejdy commented
> > ![obrazek](https://user-images.githubusercontent.com/82664677/232889438-0a15251f-e08b-45bf-b946-fa799d13faee.png)
> > Něco tam nesedí.
> 
> Udělal jsi čistou instalaci balíčků, nebo to jen spustil znovu na existujících? Vypadá to, že tam máš z nějakého důvodu starý jeden (klíčový) balíček - typescript.

No, smazal jsem tu složku, naklonoval to tam znova a po instalaci npm jsem si to přepnul na tu správnou větev (protože z hlavní větve jsem nečekaně nic nevykoukal:-)).

2023-04-19 08:53 UTC, Grejdy approved these changes
Tak už mi to funguje. Nevím, co jsem předtím dělal špatně. Možná jsem jenom nezmáčkl „synchronizovat“, nebo tak něco.:-)

2023-04-19 09:07 UTC, SmallhillCZ commented
Tak super. Kdyby se zas něco rozbilo, dej vědět — já to spouštím v kontejneru, takže to mám trochu jinak, tak bych na to nepřišel, že to nefunguje.

2023-04-19 09:07 UTC, merged