Přidání návodu k odebírání kalendáře akcí
bosancz/bosan.cz pull request #574
Opened 2023-09-14 21:50 UTC by Grejdy

# Změny
Na kartě „program“ přibyl nahoře (ještě nad programem) řádek s odkazem. Odkaz otevře okýnko s návodem, jak odebírat kalendář akcí včetně tří příkladů.
 - 

# Testovací scénář

1. Otevři si test.bosan.cz a obnov stránku.
    - Windows: `CTRL + F5`
    - Mac: `⌘ Cmd + ⇧ Shift + R`
2. Zkontroluj, že to tak opravdu je…

 Po otestování vždy napiš feedback, buď `Approve review`, nebo `Request changes`. Návod zde: [Jak na testování](https://github.com/bosancz/bosan.cz/wiki/Jak-na-testov%C3%A1n%C3%AD%3F)

2023-09-14 21:53 UTC, Grejdy commented
Jo a myslím, že tam možná bude problém s velikostí obrázků na menší obrazovce - třeba na mobilu a nepřišel jsem na to, jak to vyřešit.
A pokoušel jsem se to udělat tak, aby byly příklady vyrolovávací pomocí bootstrap collapse, ale myslím, že tahle komponenta tam ještě není a já jí tam neumím přidat… prostě mi to nefungovalo, tak je to jenom pod sebou:-)

2023-09-15 08:20 UTC, DavidTvrdy commented
test.bosan.cz .. 404 page not found

2023-09-15 10:33 UTC, Grejdy commented
> > test.bosan.cz .. 404 page not found
> 
> už to funguje

Kde byl problém?

2023-09-15 10:35 UTC, DavidTvrdy commented
Random poznámka - dal bych ten odkaz na návod třeba jen na slova "odběr akcí" 
.. Nastav si ODBĚR AKCÍ přímo do svého kalendáře

2023-09-15 10:43 UTC, Grejdy commented
> Random poznámka - dal bych ten odkaz na návod třeba jen na slova "odběr akcí" .. Nastav si ODBĚR AKCÍ přímo do svého kalendáře

Good point. Už nevím, co jsem tam napsal, ale bylo to dlouhý:-)

2023-09-15 10:53 UTC, Grejdy commented
A možná, když na to tak koukám, tak ještě třeba v rámci příští branche trošku přepíšu jeden bod v tom Contributing.md (on asi aktuálně není nikdo, kdo by to četl, ale ať je to aktuální…), zase předělali prostředí VS Code a chvíli mi trvalo, než jsem zjistil, proč mi to hází chybu:-)

2023-09-15 11:00 UTC, DavidTvrdy requested changes
Okno s návodem se musí scrollovat do strany - nemůže být prostě širší? Je docela úzké. Proč je tam vevnitř to šedé pole s obsahem, nemůže to být rovnou v tom okně (nebo prostě aby tam nebyly dva posouvače do strany)?

Třetí příklad mi přijde zbytečný... Nevím, jestli někdo používá speciální aplikace na kalendář a neumí si do něj kalendáře přidat.

Text podle mě všude do bloku, ne na střed.

Pár drobných poznámek v komentářích u kódu.

Velikost obrázků na mobilu mi nevadí, nepřijdou mi nepřiměřeně velké, naopak pro zvětšení se dá zoomovat.

![image](https://github.com/bosancz/bosan.cz/assets/47000101/bbad5a4b-9442-4952-8737-16a350bd6736)

2023-09-15 11:24 UTC, Grejdy commented
> Okno s návodem se musí scrollovat do strany - nemůže být prostě širší? Je docela úzké. Proč je tam vevnitř to šedé pole s obsahem, nemůže to být rovnou v tom okně (nebo prostě aby tam nebyly dva posouvače do strany)?
> 
> Třetí příklad mi přijde zbytečný... Nevím, jestli někdo používá speciální aplikace na kalendář a neumí si do něj kalendáře přidat.
> 

ad 1) myslím, že to šedé pole by se z toho vyhodit dalo, ale ve stejném dizajnu je většina webu… a ty posuvníky jsem se z toho snažil dostat a nepovedlo se mi to, ať jsem se to tam snažil zmenšovat kde to šlo… ale jsou tam zbytečné. Když s tím, člověk posouvá, už tam žádný obsah není… a širší už to okno je:-) Ale můžu se ještě zkusit podívat, jestli s tím něco nesvedu:-)

ad 2) Tahle konkrétní aplikace je asi 10 nejstahovanější na celém google play a myslím, že velká část lidí, co používá něco jiného než GCalendar se nikdy nesetkala s žádným sdíleným kalendářem, co by měli potřebu tam přidávat (většina bude prostě používat jen lokálně uložený kalendář)… ale možná se pletu.:-)

ad 3) Nevím, jestli všude, ale minimálně části by zarovnání do bloku slušelo… mrknu na to.

ad 4) Poznámky vyřeším

ad 5) To je supr. Ze začátku jsem tam trošku bojoval s tím, aby se tam vůbec vešly i na počítači a nebyl jsem si jistý, jestli je nebude potřeba zmenšit pro menší obrazovku víc, než pro velkou…

2023-09-15 11:56 UTC, Grejdy commented on web/src/app/components/calendar-sync-manual/calendar-sync-manual.component.html
> +      <p style="color: darkgray;"><i>Postup v různých aplikacích se může trochu lišit, ale tohle je ten asi nejobvyklejší. Může se ale stát, že bude potřeba ještě něco: třeba u google calendar se ten
…poměr slučovací ->čárka tam nepatří (ale jistej jsem si nebyl, musel jsem si to najít:-)

2023-09-15 12:03 UTC, Grejdy commented on web/src/app/components/calendar-sync-manual/calendar-sync-manual.component.html
> +        <li>Pokud už nevidíš akce v kalendáři, zkus zmáčknout „Synchronizovat“, nebo tento kalenrář povolit/zobrazit.</li>
Pravda, tady se víc hodí varianta bez čárky:-)

2023-09-15 12:03 UTC, DavidTvrdy commented on web/src/app/components/calendar-sync-manual/calendar-sync-manual.component.html
> +      <p style="color: darkgray;"><i>Postup v různých aplikacích se může trochu lišit, ale tohle je ten asi nejobvyklejší. Může se ale stát, že bude potřeba ještě něco: třeba u google calendar se ten
vidíš, máš asi pravdu, to jsem nevěděl, že časová posloupnost se bere jako slučovací

2023-09-15 12:10 UTC, Grejdy commented
Něco jsem vyřešil, nevím, jestli to s tím zarovnání do bloku vypadá líp, nebo jestli to třeba na některé řádky nedávat…
S těma posuvníkama si ještě zkusím pohrát, ale nevím, jestli budu mít úspěch:-)

2023-09-15 12:14 UTC, DavidTvrdy commented on web/src/app/components/calendar-sync-manual/calendar-sync-manual.component.html
> +      <p><b>Google calendar</b> je potřeba nastavit nejdříve ve webovém rozhraní.<br><i>Otevřeme si tedy Google kalendář v prohlížeči, u kategorie „jiné kalendáře“ klikneme na „+“ (přidat další kalen
Ještě tady v tom tučném velké C

2023-09-15 12:17 UTC, Grejdy commented on web/src/app/components/calendar-sync-manual/calendar-sync-manual.component.html
> +      <p><b>Google calendar</b> je potřeba nastavit nejdříve ve webovém rozhraní.<br><i>Otevřeme si tedy Google kalendář v prohlížeči, u kategorie „jiné kalendáře“ klikneme na „+“ (přidat další kalen
Á, vidíš.:-)

2023-09-15 12:41 UTC, Grejdy commented
Přišel jsem na to, jak odstranin ten vnější posuvník… problémy tam dělal ten křížek… snad to neudělá nějaký nepořádek třeba na mobilu, ale snad by nemělo…

2023-09-15 13:06 UTC, Grejdy commented
> Tak horizontálních posuvníků se mi povedlo zbavit (u toho druhého nevím, proč tam byl, ale povedlo se mi ho odstranit… co přesně dělá class="row"? Z nějakého důvodu to strkalo ten text moc do šířky.

2023-09-15 13:51 UTC, SmallhillCZ commented
> > > test.bosan.cz .. 404 page not found
> > 
> > 
> > už to funguje
> 
> Kde byl problém?

v noci byl nějaký problém se serverem a ten test nějak nenaběhl, netuším proč

2023-09-15 14:16 UTC, Grejdy commented
> > > > test.bosan.cz .. 404 page not found
> > > 
> > > 
> > > už to funguje
> > 
> > 
> > Kde byl problém?
> 
> v noci byl nějaký problém se serverem a ten test nějak nenaběhl, netuším proč

Myslím, že totéž je i u interní (resp. když jsem to zkoušel, tak se mi střídavě nezobrazila interní a veřejná sekce)

2023-09-16 19:19 UTC, DavidTvrdy approved these changes
Za mě takhle dobrý

2023-09-16 19:19 UTC, merged